# Whether to bridge usernames instead of display names, even if a full
# display name is available
prefer_usernames: false

mattermost:
  username: matrix@example.com
  password: hunter2
  instance: mattermost.example.com
  # Uncomment to skip some channels from the export
  # skip_channels:
  #   - "po9ucmm6wirjbnc3irjybc333y"

  backfill:
    # What to backfill as a Matrix "topic". Accepted options are 'header' or 'purpose'
    # to use those Mattermost fields, 'both' to treat either header changes or purpose
    # changes as topic changes, or 'auto' to choose only one of them depending on what
    # events the channel has.
    topic_equivalent: auto

    # Given that Mattermost does not have a separate concept of "reply" and "thread",
    # you can configure how to backfill them. Accepted options are 'reply' to bridge
    # them to Matrix as replies to the latest message in the Mattermost thread, 'thread'
    # to bridge Mattermost threads as Matrix threads, and 'auto' to bridge them as replies
    # if the thread is small enough
    thread_equivalent: auto

    # If you chose 'auto', what is the minimum number of messages to use a thread instead
    # of replies?
    # thread_threshold: 3

    # List of channels to always thread, regardless of the above options
    # always_thread:
    #   - 8qztonpgkf8gffqddckrkpfyic
    #   - pb7dp9psgpywuj567h73fdnxnr
    #   - oi8nnwbn3trfjgc5cntzqc6ucc
  
  bridge:
    # Similarly, what to bridge as a Matrix "topic".
    # Accepted options are 'header', 'purpose' and 'both' but not 'auto'
    topic_equivalent: both

    # Similarly, how to bridge Mattermost threads to Matrix
    # Accepted options are 'reply' and 'thread', but not 'auto'
    thread_equivalent: thread


matrix:
  # See https://spec.matrix.org/v1.6/application-service-api/#registration
  hs_token: Please generate one with pwgen -s 64 1
  as_token: Please generate (another) one with pwgen -s 64 1

  # Homeserver name, for MXIDs
  homeserver: example.com

  # The homeserver URL, where you can actually reach the Matrix REST API
  homeserver_url: https://matrix-synapse.example.com

  # Whether to enable the bridge at all
  enable_bridge: false

  # Where should the appservice host its REST API?
  listen_address: 127.0.0.1
  listen_port: 29782

  # User MXIDs to add and give admin in created rooms or spaces
  users:
    - "@admin:example.com"
    - "@neo:example.com"

  # Whether to skip already existing rooms when importing
  # Change this to allow using rooms that you created, with the caveat that if you
  # run the import scripts twice, it will import all messages twice.
  skip_existing: true

  # Format to use for display names
  #   {name} will replaced with the display name (if available) or username, depending on
  #   what prefer_usernames is set to. {platform} will be replaced with the word Mattermost
  #   Examples: "[{platform}] {name}", "{name}" for "[Mattermost] Gabriel R." and "Gabriel R."
  display_name_format: "{name} - {platform}"

  # Prefix to use for aliases; uncomment to change
  # room_prefix: _mattermost_

  # Prefix to use for localparts of bridged users; uncomment to change
  # user_prefix: _mattermost_

  # The username to allocate for this application service
  # username: mattermostbot
